### ISSUE TITLE
Xanitizer plugin Error:Fail to get the canonical path

### ISSUE THREAD

**Issue by Jane151013** [RIGS-IT/sonar-xanitizer#5]
Hi all,
I have encountered a problem when deploy the plugin of Xanitizer in sonar.My OS and software versions are as follows:
OS:win7
sonarqube:5.6.6
Xanitizer:3.0
Xanitizer plugin:sonar-xanitizer-plugin-1.3.3.jar
After I ran Xanitizer,generated the xml report and puted it in the repository of my project.When I ran the sonar-scanner,I encountered the error as below:
INFO: Sensor XanitizerSensor
INFO: Reading Xanitizer findings from 'E:\Jenkins\workspace\oidd-portal\Xanitizer-Findings-List.xml' for project 'oidd portal'
INFO: Processing Xanitizer analysis results of 2017-04-19 16:08:52
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 2:54.316s
INFO: Final Memory: 59M/664M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Fail to get the canonical path of E:\Jenkins\workspace\oidd-portal\C:\Users\Administrator\.Xanitizer\XanitizerProject-oiddPortal\jspWork\java\xanitizer\generatedFromJsp\WEB_002dINF\jsp\dataStorage\ability_005fadd_jsp.java
	at org.sonar.api.utils.PathUtils.canonicalPath(PathUtils.java:57)
	at org.sonar.api.scan.filesystem.PathResolver.relativePath(PathResolver.java:82)
	at org.sonar.api.batch.fs.internal.AbsolutePathPredicate.get(AbsolutePathPredicate.java:52)
	at org.sonar.api.batch.fs.internal.DefaultFileSystem.inputFiles(DefaultFileSystem.java:164)
	at com.rigsit.xanitizer.sqplugin.XanitizerSensor.mkInputFileOrNullFromPath(XanitizerSensor.java:313)
	at com.rigsit.xanitizer.sqplugin.XanitizerSensor.mkInputFileOrNull(XanitizerSensor.java:246)
	at com.rigsit.xanitizer.sqplugin.XanitizerSensor.generateIssueForFinding(XanitizerSensor.java:182)
	at com.rigsit.xanitizer.sqplugin.XanitizerSensor.createIssuesAndMeasures(XanitizerSensor.java:149)
	at com.rigsit.xanitizer.sqplugin.XanitizerSensor.analyse(XanitizerSensor.java:138)
	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
	at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.io.IOException:
	at java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
	at java.io.File.getCanonicalPath(File.java:618)
	at org.sonar.api.utils.PathUtils.canonicalPath(PathUtils.java:55)
	... 37 more

I don't know this error is generated because of my configurations or the bug of the plugin itself.
my configure of sonar-project.properties is as follows:
sonar.projectKey=oidd_portal
sonar.projectName=oidd portal
sonar.projectVersion=1.0
sonar.sources=.
sonar.java.source=1.7
sonar.sourceEncoding=UTF-8
sonar.java.binaries=webapp/WEB-INF/classes/
sonar.java.libraries=target/OIDD-01.001.001/WEB-INF/lib/*.jar

Your thoughts and support is highly appreciated.

Regards Jane

**Comment by normanwenzel** [comment]
It surely is a bug in the plugin or the underlying SonarQube framework, which for any reasons thinks that the given absolute path is relative. We will fix this, but please be patient, at the moment we are quite busy.

**Comment by Jane151013** [comment]
Hi norman，
Thank you for your response.
By the way,the path of C:\Users\Administrator is not exit in each computer,such as mine.So please take it into consideration，thank you.

**Comment by Jane151013** [comment]
Hi norman，
I noticed that you have been closed this issue.So can you tell me how to solve my problem?
The version of this plugin is still 1.3.3 and there is no any commit about source code after I asked my questions.So I don.t know how to solve it.
Waiting for your answers urgently，thank you. @normanwenzel

**Comment by hannikrix** [comment]
Hello Jane,

no I haven't closed the issue, it was closed by you (" Jane151013 closed this on 20 Apr") ;)

I am sorry that you have to wait for so long, but at the moment we have no time for a new release of the SonarQube plugin. Since Xanitizer is free to use we must do other projects to pay our bills, I hope you can understand this. So please be a little bit more patient, I promise you that there will be an update.

**Comment by normanwenzel** [comment]
Hello Jane,

no I haven't closed the issue, it was closed by you (" Jane151013 closed this on 20 Apr") ;)

I am sorry that you have to wait for so long, but at the moment we have no time for a new release of the SonarQube plugin. Since Xanitizer is free to use we must do other projects to pay our bills, I hope you can understand this. So please be a little bit more patient, I promise you that there will be an update.

**Comment by normanwenzel** [comment]
FIXED in 1.4.0
